### ISSUE TITLE
Alpine: unable to login

### ISSUE THREAD

**Issue by lbartoletti** [cbsd/cbsdfile-recipes#8]
@olevole I can't login to the alpine jail.

```shell
cd /path/to/cbsdfile-recipes/jail/alpine
cbsd up
cbsd jlogin jname=alpine
```
returns:

```
found CBSDfile: /path/to/cbsdfile-recipes/jail/alpine/CBSDfile
exec jlogin to: alpine
Unknown environment, unable to login
```

**Comment by olevole** [comment]
please update cbsd to the latest version: 13.1.15 (e.g. from ports tree)

**Comment by lbartoletti** [comment]
Ah thanks! Indeed, it requires CBSD 13.1.15

BTW, Do you know how to add these files/permissions inside the chroot jailed?

```
mknod -m 666 /dev/full c 1 7
mknod -m 666 /dev/ptmx c 5 2
mknod -m 644 /dev/random c 1 8
mknod -m 644 /dev/urandom c 1 9
mknod -m 666 /dev/zero c 1 5
mknod -m 666 /dev/tty c 5 0
```

I can mkndo inside a chroot on a base system but not inside a jail.
This is required for some operations (like git clone...)

The reference: https://gist.github.com/zenlor/52a70eaafa5563905546bc83deca7e2c#file-alpine-chroot-sh-L99-L109

**Comment by olevole** [comment]
@lbartoletti you mean mkod can't be done inside a jail (e.g. via jexec)? CBSD has the ability to use various hooks at different stages of creating and launching the environment, may be this helps: https://github.com/cbsd/cbsdfile-recipes/commit/879773359057fb1f7135a12b3cbc1576f71c8f68


Can U check this?  unfortunately I can't check it myself right now

**Comment by mekanix** [comment]
I solved it for Reggae by using [devfs.rules](https://github.com/cbsd/reggae/blob/master/templates/devfs.rules). For some of the past experiments I had this:
```
[cbsd=7]
add include $devfsrules_hide_all
add include $devfsrules_unhide_basic
add include $devfsrules_unhide_login
add path 'bpf*' unhide
add path 'pf*' unhide mode 0660 group 216
```
The 216 can be the group name, also. I hope it helps.

**Comment by olevole** [comment]
I'm wondering if there is any difference in `mknod` between FreeBSD and Linux. Because alpine is a linuxulator-based container and we have(?) to call linux-mknod ?
